### PR TITLE
Smart Polls (EasPollActionModule)

### PR DESCRIPTION
**Pull request by iPaulPro**
# Verify my module

- Module type: open action
- Module name: EasPollActionModule
- Module address: 0x3d06AA6ca4FC7eE0D5581B85CB52CA7714175e43
- My module is immutable: yes
- My module is using an upgradeable proxy: no
- My module has been registered on the registry: yes
- My module has been verified on the block explorer: yes
- My module is a paid action so uses currencies: no
- Transaction hash of a successful `act` or `actWithSig` on Lens Testnet (Mumbai) contracts: 0x0449c0a3574e7995a245ea9e9c3bd9704f4f1d28c181dd05b17400159700b92f
- Summary of my module: Transforms a Lens Publication into an onchain poll using Ethereum Attestation Service (EAS) for voting.
- I have updated the module type json file: yes

### CODE REVIEW

**Comment by iPaulPro** [comment]
I've published a repo that includes the contract source code as well as a Typescript helper library at [SmartPolls](https://github.com/iPaulPro/SmartPolls)

Using the `eas-poll-action-module` library makes creating polls as simple as
```typescript
import { OpenActionModuleInput } from "@lens-protocol/client";
import { createPollActionModuleInput } from "eas-poll-action-module";

const pollAction: OpenActionModuleInput = createPollActionModuleInput({
  options: ["Option A", "Option B", "Option C", "Option D"]
});
```

And creating the Vote Action as simple as
```typescript
import { ActOnOpenActionRequest } from "@lens-protocol/client";
import { createVoteActionRequest } from "eas-poll-action-module";

const voteAction: ActOnOpenActionRequest = createVoteActionRequest({
  publicationId: "0x01-0x02",
  optionIndex: 1,
});
```

The library also includes helper functions for calling the EAS GraphQL API. E.g.

```typescript
import { createVoteCountForOptionQueryVariables, getVoteCountForOption } from "eas-poll-action-module";

const variables = createVoteCountForOptionQueryVariables("0x01-0x02", 1);
const count = await getVoteCountForOption(variables);
```

**Comment by bigint** [comment]
Woah excited for this one!!!

**Comment by iPaulPro** [comment]
> Woah excited for this one!!!

❤️ I've got a PR for Hey that replaces Snapshot polls basically ready to go! Waiting on verification but will submit a draft soon to get feedback.

**Comment by donosonaumczuk** [comment]
Looks good

**Comment by bigint** [comment]
> I've published a repo that includes the contract source code as well as a Typescript helper library at [SmartPolls](https://github.com/iPaulPro/SmartPolls)
> 
> Using the `eas-poll-action-module` library makes creating polls as simple as
> 
> ```ts
> import { OpenActionModuleInput } from "@lens-protocol/client";
> import { createPollActionModuleInput } from "eas-poll-action-module";
> 
> const pollAction: OpenActionModuleInput = createPollActionModuleInput({
>   options: ["Option A", "Option B", "Option C", "Option D"]
> });
> ```
> 
> And creating the Vote Action as simple as
> 
> ```ts
> import { ActOnOpenActionRequest } from "@lens-protocol/client";
> import { createVoteActionRequest } from "eas-poll-action-module";
> 
> const voteAction: ActOnOpenActionRequest = createVoteActionRequest({
>   publicationId: "0x01-0x02",
>   optionIndex: 1,
> });
> ```
> 
> The library also includes helper functions for calling the EAS GraphQL API. E.g.
> 
> ```ts
> import { createVoteCountForOptionQueryVariables, getVoteCountForOption } from "eas-poll-action-module";
> 
> const variables = createVoteCountForOptionQueryVariables("0x01-0x02", 1);
> const count = await getVoteCountForOption(variables);
> ```

Hey, at Hey.xyz we try to avoid using lot of libs, would be great to have bare skeleton implementation docs like mentioning encode params and its details, something like this

Screenshot 2024-04-12 at 4 20 52 PM

**Comment by iPaulPro** [comment]
> > I've published a repo that includes the contract source code as well as a Typescript helper library at [SmartPolls](https://github.com/iPaulPro/SmartPolls)
> > Using the `eas-poll-action-module` library makes creating polls as simple as
> > ```ts
> > import { OpenActionModuleInput } from "@lens-protocol/client";
> > import { createPollActionModuleInput } from "eas-poll-action-module";
> > 
> > const pollAction: OpenActionModuleInput = createPollActionModuleInput({
> >   options: ["Option A", "Option B", "Option C", "Option D"]
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And creating the Vote Action as simple as
> > ```ts
> > import { ActOnOpenActionRequest } from "@lens-protocol/client";
> > import { createVoteActionRequest } from "eas-poll-action-module";
> > 
> > const voteAction: ActOnOpenActionRequest = createVoteActionRequest({
> >   publicationId: "0x01-0x02",
> >   optionIndex: 1,
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The library also includes helper functions for calling the EAS GraphQL API. E.g.
> > ```ts
> > import { createVoteCountForOptionQueryVariables, getVoteCountForOption } from "eas-poll-action-module";
> > 
> > const variables = createVoteCountForOptionQueryVariables("0x01-0x02", 1);
> > const count = await getVoteCountForOption(variables);
> > ```
> 
> Hey, at Hey.xyz we try to avoid using lot of libs, would be great to have bare skeleton implementation docs like mentioning encode params and its details, something like this
> 
> Screenshot 2024-04-12 at 4 20 52 PM

I'm aware, that's why I'm [working on a PR](https://github.com/heyxyz/hey/pull/4812) that integrates it directly without using the library. 🙂 The idea of the library is also that it provides sufficient working code, even if you don't want to use it directly. 

The [Smart Polls](https://github.com/iPaulPro/smart-polls) repo has a bunch of details on the calldata, as well as links to the metadata and working code for integration.

**Comment by iPaulPro** [comment]
What do I have to get this verified?

**Review by joshstevens19 — APPROVED** [review]

**Pull request merged**
