### PR TITLE
feat: add RaveShareMintOAV0 details

### PR DESCRIPTION
**Pull request by thearyanag**
# Verify my module

- Module type: open action
- Module name: RaveShareMintOAV0
- Module address: https://polygonscan.com/address/0x410688fc60028C805Bdf8592A6504A0096927911#code
- My module is immutable: yes
- My module is using an upgradeable proxy: no
- My module has been registered on the registry: yes
- My module has been verified on the block explorer: yes
- My module is a paid action so uses currencies: yes
- Summary of my module: The module accepts payment in wMATIC and sends it to our platform address, the amount is calculated using chainlink feed and is equivalent to 0.000777 ETH + 10% , as soon as payment is done, an event is sent which triggers our server to mint NFT ( zora ) to the user address, the chain can also be set during intialize action.
- I have updated the module type json file: yes

### CODE REVIEW

**Comment by donosonaumczuk** [comment]
Some comments:

1) Any reason why `processPublicationAction`  is not `onlyHub`  restricted? Is that intended?
```solidity
    function processPublicationAction(
        Types.ProcessActionParams calldata params
    ) external override returns (bytes memory) {
        // ...
    }
```

2) Seems that these events are not used, in case you want to remove them:
```solidity
    event Log(string variable, string message);
    event Log(string variable, address message);
    event Log(string variable, int message);
```

**Comment by thearyanag** [comment]
hey @donosonaumczuk , 1/2 were for testing purpose, I have updated the PR with the updated contract address, which you can find at https://polygonscan.com/address/0x410688fc60028c805bdf8592a6504a0096927911#code

**Comment by donosonaumczuk** [comment]
Great, looks good to me now @thearyanag

**Comment by joshstevens19** [comment]
Needs a rebase please @thearyanag

**Comment by vicnaum** [comment]
Instead of
```
        if (!MODULE_GLOBALS.isErc20CurrencyRegistered(currency)) {
            revert CurrencyNotWhitelisted();
        }
```

you can verify that `MODULE_GLOBALS.verifyErc20Currency(currency)` returns `true` - this will automatically register a currency if it wasn't done before (making the module use with other currencies more user-friendly)

**Comment by thearyanag** [comment]
hey @joshstevens19 , did the rebases, check now

**Comment by thearyanag** [comment]
hey @vicnaum , thanks for the suggestion, that line is intended as we want to start this as a piolet module and iterate based on user feedback , in the coming module we'll open up the support for all token.

**Comment by joshstevens19** [comment]
we can merge this but you need to rebase it has conflicts with base @thearyanag

**Comment by thearyanag** [comment]
hey @joshstevens19 , I did the rebase earlier , I suppose with the recent changes to the base, there were conflicts, I rebased it again, check now

**Pull request merged**
