### PR TITLE
AuctionCollectAction

### PR DESCRIPTION
**Pull request by iPaulPro**
# Verify my module

- Module type: open action
- Module name: AuctionCollectAction
- Module address: [0x6511B9CE24E1198F4803e652B58ABB687484A6d0](https://polygonscan.com/address/0x6511B9CE24E1198F4803e652B58ABB687484A6d0#code)
- My module is immutable: yes
- My module is using an upgradeable proxy: no
- My module has been registered on the registry: yes
- My module has been verified on the block explorer: yes
- My module is a paid action so uses currencies: yes
- Transaction hash of a successful `act` or `actWithSig` on Lens Testnet (Amoy) contracts: [0x625f5b196d05bc10098c6660e6374a10a87a43ed4ae0252c5b16b2487c304938](https://amoy.polygonscan.com/tx/0x625f5b196d05bc10098c6660e6374a10a87a43ed4ae0252c5b16b2487c304938)
- Summary of my module: English auctions for 1 of 1 Lens Collects
- I have updated the module type json file: yes

Github repo for the contracts: https://github.com/mvanhalen/scaffold-lens-auction

This action has a robust set of unit tests that are all passing: https://github.com/mvanhalen/scaffold-lens-auction/blob/6c1449eb7152985a77c5c75292fe3690a508989d/packages/hardhat/test/AuctionCollectAction.ts

### CODE REVIEW

**Comment by donosonaumczuk** [comment]
I am so happy to see the Auction Collect bringing back to life, I've always thought that this feature is so cool. I want to thank you guys (@iPaulPro @mvanhalen) for adding me to the authors.

I will be posting some comments here as part of the review

**Comment by donosonaumczuk** [comment]
**[Comment 1]**

Even when it should be unlikely to happen, profiles can change hands between the last bid placed and the end of the auction. As a consequence, the best idea would be to store the Profile ID of the winner, and determine the Owner of that profile when minting the NFT.

Given that `Winner::transactionExecutor` does not seem to be used, I suggest to replace the whole `Winner` struct by just a `uint256` holding the Profile ID.

**Comment by donosonaumczuk** [comment]
**[Comment 2]**

There are some unused imports, in case you want to get rid of them.

image

**Comment by iPaulPro** [comment]
> **[Comment 1]**
> 
> Even when it should be unlikely to happen, profiles can change hands between the last bid placed and the end of the auction. As a consequence, the best idea would be to store the Profile ID of the winner, and determine the Owner of that profile when minting the NFT.
> 
> Given that `Winner::transactionExecutor` does not seem to be used, I suggest to replace the whole `Winner` struct by just a `uint256` holding the Profile ID.

This is interesting, as it's opposite of what I would expect, though I'm not sure it's necessarily intuitive either way. If we think about the NFT as being owned by the address, and *not* by the profile, then my instinct is that it should be minted by the address that placed the bid (the profile owner at the time of the bid). This seems like a safer choice to me, especially when we consider that these sales might be presented in a way where the Lens profile being used is not clear.

Also, how does this work with Open Actions [executed without a profile](https://docs.lens.xyz/docs/open-actions-without-a-profile)? In that case, is the profile owner address the actual bidder, or is it the transaction executor? If the latter, should we only be using the executor?

Getting rid of `transactionExecutor` might makes sense, however, the bidder address and profile ID are used in many places, and storing both avoids many calls to `IERC721(PROFILE_NFT).ownerOf()`, so I thought it was cleaner to store both. Depending on your answer to above, it'll be more clear what the `Winner` struct should look like.

**Comment by donosonaumczuk** [comment]
> Also, how does this work with Open Actions [executed without a profile](https://docs.lens.xyz/docs/open-actions-without-a-profile)? In that case, is the profile owner address the actual bidder, or is it the transaction executor? If the latter, should we only be using the executor?

That's a really important and good question, because the actual bidder will NOT be the owner NOR the transaction executor in that case. I am discussing with @vicnaum what would be the best solution for this case.

Because you are implementing this module as an `IPublicationActionModule`, not as an `ICollectModule`.

**Comment by vicnaum** [comment]
1. For complicated actions as Auction it's best to only use it with a profile - just to make it consistent (so the UI's can show that this @profile is winning, etc).
2. If you want to use it without a profile, then as @donosonaumczuk said above - the PublicActProxy will be the actorProfile and the owner of the profile - so you will need some kind of `nftRecipientAddress` in your Winner struct that you will pass along with the `amount` in `actionModuleData` - and then record it, and then mint the NFT to that recorded address.
3. But the above will allow anyone to bid and specify any nftRecipientAddress - which might be confusing, but also can be a good thing (like people placing bids from many profiles for some charity winner address). I don't know if this is a good idea, cause the UI's will also have trouble displaying and separating the profile bidder from the actual NFT recipient (where the NFT goes when the auction ends).
4. Considering the above - it is a good idea to just always use profiles (as said in 1), as you can see otherwise everything gets confusing really fast.
5. I would also recommend not using the separate `claim` function - because it might be hard to get support from all the UIs and the API. Better to make everything in the `processCollect` function, and just check if the auction is running - then bid, if it's over - then claim. And the claim can be called by anyone (as the winner is already recorded, NFT will still be minted to the winner).
6. As @donosonaumczuk said - despite being auction, this module might work well as a CollectModule (under the CollectPublicationAction) - because I don't see any custom NFT being minted, or I'm missing something - but CustomCollectNFT is very similar to our CollectNFT - please explain the details if I'm wrong.
7. That way you will probably get more UI support, if it's a CollectModule.

**Comment by iPaulPro** [comment]
> 5. I would also recommend not using the separate `claim` function - because it might be hard to get support from all the UIs and the API. Better to make everything in the `processCollect` function, and just check if the auction is running - then bid, if it's over - then claim. And the claim can be called by anyone (as the winner is already recorded, NFT will still be minted to the winner).
> 6. As @donosonaumczuk said - despite being auction, this module might work well as a CollectModule (under the CollectPublicationAction) - because I don't see any custom NFT being minted, or I'm missing something - but CustomCollectNFT is very similar to our CollectNFT - please explain the details if I'm wrong. _UPD_: Ok, I see that its probably used because of custom Name and Symbol - is that correct?
> 7. That way you will probably get more UI support, if it's a CollectModule.

We chose a claim function for a few reasons:

1. `CollectPublicationAction` doesn't allow us to prevent the minting of a `CollectNFT` without reverting the entire `process` call. This means we can't actually accept bids without issuing an NFT for each bid.
2. Allowing the claim to be called from any address means that the app can call it, automating the process for the user.
3. It's a common pattern used in NFT marketplaces like Foundation.
4. It makes more sense to sponsor the gas for bids, since those are likely to be more common.

The main reason we're using `CustomCollectNFT` is to allow the author to specify the token name, symbol, and royalty rate. I suspect that OpenSea simply hides all tokens with the symbol `LENS-COLLECT` and this is a feature we believe will be desirable for those looking to release on Lens over other marketplaces.

**Comment by vicnaum** [comment]
> 1. `CollectPublicationAction` doesn't allow us to prevent the minting of a `CollectNFT` without reverting the entire `process` call. This means we can't actually accept bids without issuing an NFT for each bid.
That's correct. So yes, it's better to be an Action module, not a Collect module.

> 2. Allowing the claim to be called from any address means that the app can call it, automating the process for the user.
> 3. It's a common pattern used in NFT marketplaces like Foundation.
> 4. It makes more sense to sponsor the gas for bids, since those are likely to be more common.
Yes, that's why I also recommend in (5), and it can be in a processAction (but maybe not - it's not so critical, let's see what @donosonaumczuk says)
 
> The main reason we're using `CustomCollectNFT` is to allow the author to specify the token name, symbol, and royalty rate. I suspect that OpenSea simply hides all tokens with the symbol `LENS-COLLECT` and this is a feature we believe will be desirable for those looking to release on Lens over other marketplaces.
Got it. Then I have another suggestion: you can add an optional metadata parameter along with name and symbol, so one can not only collect lens posts, but also mint any custom NFTs with custom metadata (image, etc).

**Comment by iPaulPro** [comment]
> Yes, that's why I also recommend in (5), and it can be in a processAction (but maybe not - it's not so critical, let's see what @donosonaumczuk says)

But if it's in `processAction` it can only be called by Lens Hub, which means an extra step of constructing an `act` rather than simply allowing anyone to call `claim`. I'm also generally hesitant to add more complexity to the process ABI, if it can be avoided.

> Got it. Then I have another suggestion: you can add an optional metadata parameter along with name and symbol, so one can not only collect lens posts, but also mint any custom NFTs with custom metadata (image, etc).

`CustomCollectNFT` works just like `CollectNFT` in that it uses the metadata of the Lens publication, so any `marketplace` metadata provided when publishing will be used as the ERC-721 metadata. You're saying there may be utility in allowing the publisher to specify different metadata altogether? It's not immediately clear to me why this would be useful enough to diverge from the existing pattern, but it would be easy enough to add. Could you elaborate on this?

**Comment by vicnaum** [comment]
> But if it's in processAction it can only be called by Lens Hub, which means an extra step of constructing an act rather than simply allowing anyone to call claim. I'm also generally hesitant to add more complexity to the process ABI, if it can be avoided.

This might be true. If it can be guaranteed that there will be some app that will call the `claim` after auction ends (so the user receives the NFT immediately) or some UI that will allow users to do that - then yes, why not.

> You're saying there may be utility in allowing the publisher to specify different metadata altogether? It's not immediately clear to me why this would be useful enough to diverge from the existing pattern, but it would be easy enough to add. Could you elaborate on this?

The thing here is that in it's essence, "collecting a post" is minting a copy of Lens Publication with some content in it. And that's why most marketplaces don't show this as there is too much collected posts and they prefer to hide those NFTs (cause it's just the copy of the post in NFT).
If the action is supposed to mint some collectibles, which are a separate NFT, not a "lens post NFT" (especially that it's not a Collect Action) - then it makes sense to allow authors to define a distinct NFT that is gonna be minted, with it's own metadata, unrelated to Lens post it was minted from (e.g. a song or a JPG). Then the post becomes just the selling/advertising place, and the NFT minted is a separate entity.

**Comment by iPaulPro** [comment]
> This might be true. If it can be guaranteed that there will be some app that will call the `claim` after auction ends (so the user receives the NFT immediately) or some UI that will allow users to do that - then yes, why not.

I think it's safe to say that an implementation absent the claiming part would be incomplete. 😅
 
> The thing here is that in it's essence, "collecting a post" is minting a copy of Lens Publication with some content in it. And that's why most marketplaces don't show this as there is too much collected posts and they prefer to hide those NFTs (cause it's just the copy of the post in NFT). If the action is supposed to mint some collectibles, which are a separate NFT, not a "lens post NFT" (especially that it's not a Collect Action) - then it makes sense to allow authors to define a distinct NFT that is gonna be minted, with it's own metadata, unrelated to Lens post it was minted from (e.g. a song or a JPG). Then the post becomes just the selling/advertising place, and the NFT minted is a separate entity.

This is very-much meant to be "collecting a post", and not a standalone NFT. We would have used a regular Collect Module if it was technically possible to support bids as Open Actions. We considered a two-contract approach, but that seemed too complicated.

**Comment by donosonaumczuk** [comment]
> <From @iPaulPro> CollectPublicationAction doesn't allow us to prevent the minting of a CollectNFT without reverting the entire process call. This means we can't actually accept bids without issuing an NFT for each bid.

Yes, that's why initially in [this implementation](https://github.com/lens-protocol/modules/blob/master/contracts/collect/AuctionCollectModule.sol) I did the [bid functions](https://github.com/lens-protocol/modules/blob/master/contracts/collect/AuctionCollectModule.sol#L279) as the first part of the process, and then you [execute the collect](https://github.com/lens-protocol/modules/blob/master/contracts/collect/AuctionCollectModule.sol#L191) once a winner is settled.

This was developed for Lens V1, but never seen the light because it required a lot of UI and Backend support, and back in the day there were other priorities.

In Lens V1, the Collect was a native operation in the LensHub, and the NFT was minted by the LensHub itself, before calling the `processCollect` function on the Collect Module. In V2, we stopped making the Collect a native operation, and we implemented it as a particular Publication Action.

Now in Lens V2, the LensHub role of minting the NFT was taken by the [CollectPublicationAction](https://github.com/lens-protocol/core/blob/master/contracts/modules/act/collect/CollectPublicationAction.sol#L152), before calling the `processCollect` on the Collect Module. Completely analogous, as you can see.

So, this means that the Collect Auction can be implemented as Collect Module, bids can happen through "non-standard" functions and then act through the standard function just to mint the NFT. Same as the original implementation. However, there is a complete valid point against this... :point_down: 

> <From @iPaulPro> It makes more sense to sponsor the gas for bids, since those are likely to be more common.

Correct. So, basically, following the pattern I described above, it can be developed as a Collect Module instead of an Action Module, but the issue is that the gas sponsor baked into the Lens API will apply only to the collect itself (the minting), and not the bids.

I think this is a good argument against making this feature as a Collect Module, implementing it as an Action Module instead :+1:.

Take into account that Lens API probably won't support the `claim` function, but probably UIs integrating the Auction feature will be OK supporting a "CLAIM NFT" button that calls `claim` in the contract directly.

---

Ok, so far we agreed on the interface used for the implementation. Let's move on to the last step, related to addresses being able to interact with this auction.

---

> <From @vicnaum> If you want to use it without a profile, then as @donosonaumczuk said above - the PublicActProxy will be the actorProfile and the owner of the profile - so you will need some kind of nftRecipientAddress in your Winner struct that you will pass along with the amount in actionModuleData - and then record it, and then mint the NFT to that recorded address.
But the above will allow anyone to bid and specify any nftRecipientAddress - which might be confusing, but also can be a good thing (like people placing bids from many profiles for some charity winner address). I don't know if this is a good idea, cause the UI's will also have trouble displaying and separating the profile bidder from the actual NFT recipient (where the NFT goes when the auction ends).
Considering the above - it is a good idea to just always use profiles (as said in 1), as you can see otherwise everything gets confusing really fast.

@vicnaum explained it pretty well above. Basically, we have two options.

[1] **Supporting only profiles:** Super easy, the NFT just goes to the the profile's `ownerOf`, and that's it. Basically what you already have.

[2] **Supporting profiles and addresses:** This will require to add the mechanism that @vicnaum described to the action implementation, where the NFT recipient should be passed encoded in the action custom data as part of the bid.
In addition, we will need to deploy a new PublicActProxy that handles simple payments for other actions than the CollectPublicationAction. And then also Lens API should be aware of this new PublicActProxy.

**Comment by iPaulPro** [comment]
@donosonaumczuk I think option [1] is fine. It doesn't seem worth the effort to support proxy bids.

So it sounds like green light when we:

1. Switch to using profile owner when claiming, instead of owner when the bid was placed
2. Remove unused imports and fields.

New contract should be deployed in a couple of hours, then I will update the address in this PR and ping.

**Review by donosonaumczuk — APPROVED** [review]
Ok, I reviewed the changes, it now looks correct to me - @joshstevens19 you can merge

**Comment by mvanhalen** [comment]
Thanks all @donosonaumczuk @vicnaum @iPaulPro @joshstevens19 ! Let´s rock!

**Pull request merged**
