### PR TITLE
Score open action

### PR DESCRIPTION
**Pull request by ialberquilla**
# Verify my module

- Module type: open action
- Module name: Score Open Action
- Module address: 0x98ea2bb475259bA9731c07b6Cc0421817495A68a
- My module is immutable: yes
- My module is using an upgradeable proxy: no
- My module has been registered on the registry: yes
- My module has been verified on the block explorer: yes
- My module is a paid action so uses currencies: no
- Transaction hash of a successful `act` or `actWithSig` on Lens Testnet (Mumbai) contracts: 0xc150b005753285a559fa164d642fb9fc0fc9910c5d683ffed342c3c2cea5cd6c
- Summary of my module: This module enables Libree.xyz users to create challenges by embedding a game in a post and sharing it in their network. Other users can play the game and mint their scores using the open action.
- I have updated the module type json file: yes

### CODE REVIEW

**Comment by donosonaumczuk** [comment]
In the safeMint function the next tokenId is calculated like this:

```solidity
    function safeMint(address to, string memory uri, uint256 score) public onlyOwner {
        uint256 tokenId = _nextTokenId++;
```

This makes the first tokenId to be 0, which is not wrong, but I would suggest to do it

```solidity
    function safeMint(address to, string memory uri, uint256 score) public onlyOwner {
        uint256 tokenId = ++_nextTokenId;
``` 

so the first tokenId is 1.

As I said, starting with 0 is not wrong nor goes against the ERC-721 standard. But it can be helpful in the future if you want to map something to your Score NFTs.

For example, let's say in the future you make a contract where you stake Score NFTs in exchange to something else. So you want to store the staked NFTs in a mapping:

```solidity
    mapping (address staker => uint256 tokenId) _stakedNFTs;
```

In this case, you won't be able to differentiate an address that did not stake anything versus an address that staked the tokenId 0. Of course, you can do some hacks, like storing tokenId+1, or tokenId and a boolean, but it's not ideal.

So, it's up to you, I just wanted to point it out in case you find it useful.

**Comment by donosonaumczuk** [comment]
The `ScoreOpenAction` looks good!

**Comment by ialberquilla** [comment]
> In the safeMint function the next tokenId is calculated like this:
> 
> ```solidity
>     function safeMint(address to, string memory uri, uint256 score) public onlyOwner {
>         uint256 tokenId = _nextTokenId++;
> ```
> 
> This makes the first tokenId to be 0, which is not wrong, but I would suggest to do it
> 
> ```solidity
>     function safeMint(address to, string memory uri, uint256 score) public onlyOwner {
>         uint256 tokenId = ++_nextTokenId;
> ```
> 
> so the first tokenId is 1.
> 
> As I said, starting with 0 is not wrong nor goes against the ERC-721 standard. But it can be helpful in the future if you want to map something to your Score NFTs.
> 
> For example, let's say in the future you make a contract where you stake Score NFTs in exchange to something else. So you want to store the staked NFTs in a mapping:
> 
> ```solidity
>     mapping (address staker => uint256 tokenId) _stakedNFTs;
> ```
> 
> In this case, you won't be able to differentiate an address that did not stake anything versus an address that staked the tokenId 0. Of course, you can do some hacks, like storing tokenId+1, or tokenId and a boolean, but it's not ideal.
> 
> So, it's up to you, I just wanted to point it out in case you find it useful.

Thank you for pointing this out! In this scenario, we are not using the NFTs for staking on other contracts. Nevertheless, I have implemented a new open action with this modification.

While considering the use case you mentioned, I also realized that the function we previously had for obtaining the score was based on addresses rather than tokens, so I have updated it accordingly.

I have updated the new address and description with the new address and the new amoy transaction.

**Comment by ialberquilla** [comment]
Hey @donosonaumczuk is there anything else we can do to get the module verified?

**Comment by donosonaumczuk** [comment]
> Thank you for pointing this out! In this scenario, we are not using the NFTs for staking on other contracts. Nevertheless, I have implemented a new open action with this modification.

Great!

> While considering the use case you mentioned, I also realized that the function we previously had for obtaining the score was based on addresses rather than tokens, so I have updated it accordingly.

Yeah, makes sense to be by tokenId instead of address.

> Hey @donosonaumczuk is there anything else we can do to get the module verified?

All good, I have reviewed it again. We can merge it.

**Review by donosonaumczuk — APPROVED** [review]

**Comment by ialberquilla** [comment]
> > Thank you for pointing this out! In this scenario, we are not using the NFTs for staking on other contracts. Nevertheless, I have implemented a new open action with this modification.
> 
> Great!
> 
> > While considering the use case you mentioned, I also realized that the function we previously had for obtaining the score was based on addresses rather than tokens, so I have updated it accordingly.
> 
> Yeah, makes sense to be by tokenId instead of address.
> 
> > Hey @donosonaumczuk is there anything else we can do to get the module verified?
> 
> All good, I have reviewed it again. We can merge it.

Great! 

Does it mean that it can already be used through the API?

**Comment by donosonaumczuk** [comment]
> Does it mean that it can already be used through the API?

As far as I understand, it should be available right after the CI checks pass, which already did!

**Pull request merged**
